### ISSUE TITLE
Tell what is the keyboard shortcut in README

### ISSUE THREAD

**Issue by MoezGholami** [freeauto/sketch-lorem-ipsum-2017#3]
Hi
I didn't find the shortcut to enable the plugin unless I checked the manifest. It would be good if you tell what the shortcut is in the readme.

**Comment by unstephenk** [comment]
Lol.. Whats the keyboard shortcut...?

**Comment by unstephenk** [comment]
Found it. Its Shift Ctrl L.

**Comment by richgong** [comment]
Just updated README with the shortcut. Thanks!
